Remove * on .mp4 in useDropZone
Having the * in *.mp4 causes some people not to be able to select the file but only drag and drop.

Error:
TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Extension '*.mp4' must start with '.'.