Remove * on .mp4 in useDropZone (#181)
* Remove * on .mp4 in useDropZone

Having the * in *.mp4 causes some people not to be able to select the file but only drag and drop.

Error:
TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Extension '*.mp4' must start with '.'.

* Update view-asset.en-US.mdx

Update docs for chaining `*.mp4` to `.mp4`

Co-authored-by: Chase Adams <c@cadams.io>