Access Manager V3 (#549)
* PubNub chat iteration 1

* Added redux state wrapper

* Fix for TypeError: hexoid is not a function

* Fixed fetch history bug

* Design overhaul of PubNub Chat

* Pull request fix

* server component init

* Flagged Messages Bug Fix

* Delete the secret key from .env

* added README.md for server side component

* Edit .end.example

* lock file

* updated package.json

* revert

* merge conflict fix

* axios fix

---------

Co-authored-by: Chase Adams <c@cadams.io>